### ISSUE TITLE
Fix chat scrollbar appearance

### ISSUE THREAD

**Issue by whoabuddy** [aibtcdev/aibtcdev-frontend#233]
Scrollbars used to be a CSS nightmare, I think support has gotten better and would be interesting to see latest web standards here. I like the idea of an invisible black track with orange branded top, bottom, and slider for simplicity.

![Image](https://github.com/user-attachments/assets/5db722c4-2527-431c-b5e0-7ebb2ab8a968)

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scrollbars_styling

Looks like all but Safari support it, would need some further testing.

```css
.example {
  overflow: scroll;
  scrollbar-color: orange black; /*supported in most browsers*/
  scrollbar-width: thin; /*maybe, gets pretty small*/
}
```
